In [1]:
import pandas as pd
import numpy as np

In [2]:
train = pd.read_csv('data_train.csv')

In [7]:
train.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,label
0,0,tcp,http,SF,181,5450,0,0,0,0,...,9,1.0,0.0,0.11,0.0,0.0,0.0,0.0,0.0,normal.
1,0,tcp,http,SF,239,486,0,0,0,0,...,19,1.0,0.0,0.05,0.0,0.0,0.0,0.0,0.0,normal.
2,0,tcp,http,SF,235,1337,0,0,0,0,...,29,1.0,0.0,0.03,0.0,0.0,0.0,0.0,0.0,normal.
3,0,tcp,http,SF,219,1337,0,0,0,0,...,39,1.0,0.0,0.03,0.0,0.0,0.0,0.0,0.0,normal.
4,0,tcp,http,SF,217,2032,0,0,0,0,...,49,1.0,0.0,0.02,0.0,0.0,0.0,0.0,0.0,normal.

In [32]:
protocol_type = pd.get_dummies(train['protocol_type'],drop_first=True)

In [33]:
train.append(protocol_type)

        tcp  udp
0         1    0
1         1    0
2         1    0
3         1    0
4         1    0
5         1    0
6         1    0
7         1    0
8         1    0
9         1    0
10        1    0
11        1    0
12        1    0
13        1    0
14        1    0
15        1    0
16        1    0
17        1    0
18        1    0
19        1    0
20        1    0
21        1    0
22        1    0
23        1    0
24        1    0
25        1    0
26        1    0
27        1    0
28        1    0
29        1    0
...     ...  ...
493991    1    0
493992    1    0
493993    1    0
493994    1    0
493995    1    0
493996    1    0
493997    1    0
493998    1    0
493999    1    0
494000    1    0
494001    1    0
494002    1    0
494003    1    0
494004    1    0
494005    1    0
494006    1    0
494007    1    0
494008    1    0
494009    1    0
494010    1    0
494011    1    0
494012    1    0
494013    1    0
494014    1    0
494015    1    0
494016    1    0
494017    1    0
494018    1    0
494019    1    0
494020    1    0

[494021 rows x 2 columns]